--- 
site: Brooksville
enable_backup: True

DeviceList: 
  Firewall_List: 
    FORTIGATE_BV-100F: 
      device_type: fortinet
      ip: "10.9.100.254"
    ACME-BV-WH-100E: 
      device_type: fortinet
      ip: "10.9.200.1"

  Switch_List: 
    SERVER-SWITCH: 
      device_type: brocade_fastiron
      ip: "10.9.112.1"
    BACKROOM-SWITCH: 
      device_type: brocade_fastiron
      ip: "10.9.112.2"
    

