--- 

site: "Guangzhou"
enable_backup: True

DeviceList: 
  Firewall_List: 
    ACME_GZ_100D: 
      device_type: fortinet
      ip: "192.168.1.99"

  Switch_List: 
    ACME_GZ_CORE: 
      device_type: brocade_fastiron
      ip: "192.168.196.2"
