--- 

site: "Hong Kong"
enable_backup: True

DeviceList: 
  Firewall_List: 
    ACME_HK_100D: 
      device_type: fortinet
      ip: "192.168.192.254"

  Switch_List: 
    ACME_HK_CORE: 
      device_type: brocade_fastiron
      ip: "192.168.192.2"
