--- 

site: "Keene"
enable_backup: True

DeviceList: 
  Firewall_List: 
    FF-HA-Cluster: 
      device_type: fortinet
      ip: "10.10.100.254"

  Switch_List: 
    KN-SERVER-SWITCH: 
      device_type: brocade_fastiron
      ip: "10.10.112.1"

    ACME-KN-WAREHOUSE: 
      device_type: brocade_fastiron
      ip: "10.10.112.2"
  
  
      
