--- 

site: "Laval"
enable_backup: True

DeviceList: 
  Firewall_List: 
    Fortigate 100E: 
      device_type: fortinet
      ip: "192.168.7.254"

  Switch_List: 
    ACME-QC-SERVERS: 
      device_type: brocade_fastiron
      ip: "192.168.7.1"
      
