--- 
site: Orangeville
enable_backup: True

DeviceList: 
  Firewall_List: 
    ACME-OV-FGT: 
      device_type: fortinet
      ip: "10.19.10.254"

    ACME-MF-FGT101F: 
      device_type: fortinet
      ip: "10.19.138.254"

  Switch_List: 
    ACME_CANADA_ICX: 
      device_type: brocade_fastiron
      ip: "10.19.10.1"    