--- 
site: Shelton
enable_backup: True

DeviceList: 
  Switch_List: 
    SHELTON-CORE-STACK#: 
      device_type: brocade_fastiron
      ip: "10.1.2.1"
    FF-MDF-USER-STACK: 
      device_type: brocade_fastiron
      ip: "10.1.16.1"
    ACME-HA-SWITCH: 
      device_type: brocade_fastiron
      ip: "10.1.2.4"
    FAIRFIELD-MPLS: 
      device_type: cisco_ios
      ip: "10.1.255.2"
    

  Firewall_List: 
    FF-HA-Cluster: 
      device_type: fortinet
      ip: "10.1.1.254"